### ISSUE TITLE
MSDN Plugin

### ISSUE THREAD

**Issue by schmotzle** [Vector35/community-plugins#10]
Hi,

I have written a plugin to query Microsoft MSDN documentation from Binary Ninja:

https://github.com/schmotzle/binja-msdn

Let me know if you want me to make any changes to it.

Thanks.

**Comment by psifertex** [comment]
It’s already added — did you make any other changes besides the json PR I submitted?

**Comment by schmotzle** [comment]
Hi, 
didn't notice. Nope no changes to the code beside the json ones. 
Thanks for adding it to the list.
