### ISSUE TITLE
[UpdatePlugin]  $Author $RepoName $tag

### ISSUE THREAD

**Issue by wrigjl** [Vector35/community-plugins#101]
Please update my plugin:

Author: Alex Forencich
Repo name: https://github.com/wrigjl/binaryninja-m68k.git
Release: v0.3

**Comment by psifertex** [comment]
Thanks, unfortunately one missing step left, need to actually use the UI or the `hub` command-line to create a release. Right now you'll notice v0.2 is still the "Latest Release" when you visit: https://github.com/wrigjl/binaryninja-m68k/releases

Also, not a big deal for this time, but we're trying to standardize on not having `v` in version numbers. Just something to keep in mind for future releases.

**Comment by wrigjl** [comment]
o, fixed, I think =)

**Comment by psifertex** [comment]
errr... sorta. Sorry to be the bearer of bad news: https://github.com/wrigjl/binaryninja-m68k/blob/master/plugin.json#L20

I think what happened was you meant to go for 0.2, did everything except the tag as 0.2 and it otherwise would have been fine?

**Comment by psifertex** [comment]
In your defense I've been annoyed with how tedious that process is myself so I might just create a little helper to automate that.

**Comment by wrigjl** [comment]
[bleep] [bleep] [bleeeeeeeeeeeep]... are we [bleep]ng there yet? applied the tag (0.3) and actually pushed the changes in my tree... downloaded it from the releases page and verified that is contains the fixes and the updated json.

**Comment by psifertex** [comment]
Nailed it! 

![image](https://user-images.githubusercontent.com/140215/83087516-81e7a280-a05f-11ea-93f6-85fc195d636f.png)

**Comment by wrigjl** [comment]
W00t! Thanks for the hand holding =)
