### ISSUE TITLE
[UpdatePlugin]  atxsinn3r BinjaHLILDump 1.1

### ISSUE THREAD

**Issue by atxsinn3r** [Vector35/community-plugins#103]
Please update my plugin:

Author: atxsinn3r
Repo name: BinjaHLILDump
Release: 1.1
Link: https://github.com/atxsinn3r/BinjaHLILDump/releases/tag/1.1

This update corrects the following:

* Filters outs reserved filename characters on Windows. (thanks @tekwizz123)
* Ensures file path does not exceed a certain length on Windows.
* Ensures string encoding is normalized.

**Comment by psifertex** [comment]
Thanks! Updated.
