### ISSUE TITLE
[NewPlugin] Grant Orndorff BNHook 1.1

### ISSUE THREAD

**Issue by jeffli678** [Vector35/community-plugins#104]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Grant Orndorff
Repo name: https://github.com/orndorffgrant/bnhook
Release: https://github.com/jeffli678/bnhook/releases/tag/1.1

This plugin is currently maintained by me. Issues etc should be sent to the above repo.

**Comment by psifertex** [comment]
Thanks! Updated.
