### ISSUE TITLE
[NewPlugin]  d-we binja-golang-symbol-restore 1.0

### ISSUE THREAD

**Issue by d-we** [Vector35/community-plugins#106]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: d-we
Repo name: binja-golang-symbol-restore
Release: 1.0

**Comment by psifertex** [comment]
For future reference, it's best to avoid hyphens in repository names that host python modules. Should use underscores if at all possible. Of course, changing your github username makes that a bit trickier. 😉 

Anyway, plugin has been added, thanks for the submission!
