### ISSUE TITLE
[NewPlugin]  Meador Inge https://github.com/CarveSystems/binjawa 0.5.0

### ISSUE THREAD

**Issue by meadori-cs** [Vector35/community-plugins#109]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Meador Inge
Repo name: https://github.com/CarveSystems/binjawa
Release: v.5.0

**Comment by psifertex** [comment]
Added, thanks!
