### ISSUE TITLE
Couple of simple plugins

### ISSUE THREAD

**Issue by kenoph** [Vector35/community-plugins#11]
Hi,

This is plugin using Sibyl for side effects-based function recognition:

https://github.com/kenoph/binja_sibyl

This is a simple watchdog-based automatic plugin reloader. Quite simple but it does its work:

https://github.com/kenoph/binja_reloaded

**Comment by psifertex** [comment]
Sorry I missed this one -- pulled sibyl in now, I'm going to hold off on the reloaded one for now since we plan to implement a better integrated solution shortly.
