### ISSUE TITLE
[UpdatePlugin]  bnil-graph v1.3.2

### ISSUE THREAD

**Issue by withzombies** [Vector35/community-plugins#111]
Please update my plugin: https://github.com/withzombies/bnil-graph/releases/tag/v1.3.2

Author: Me
Repo name:
Release:

**Comment by psifertex** [comment]
D'oh, somehow didn't get this updated earlier. Sorry about that.

For your next release, do you mind removing the `v` from the version? We're trying to standardize on versions without the leading character (I realize our blog and examples were previously doing this too, we've normalized those as well)
