### ISSUE TITLE
[NewPlugin] xitan binaryninja-discord-integration v0.8.0

### ISSUE THREAD

**Issue by x1tan** [Vector35/community-plugins#113]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: xitan
Repo name: [binaryninja-discord-integration](https://github.com/x1tan/binaryninja-discord-integration)
Release: v0.8.0

Thanks a lot.

**Comment by psifertex** [comment]
Thanks for the submission, added!

Minor nitpick: for your next release, do you mind removing the `v` from the version? We're trying to standardize on versions without the leading character (I realize our blog and examples were previously doing this too, we've normalized those as well)
