### ISSUE TITLE
[NewPlugin]  EliseZeroTwo Switch-Binja-Loader v1.0

### ISSUE THREAD

**Issue by EliseZeroTwo** [Vector35/community-plugins#114]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: EliseZeroTwo
Repo name: [Switch-Binja-Loader](https://github.com/EliseZeroTwo/Switch-Binja-Loader)
Release: v1.0

**Comment by psifertex** [comment]
Can you use either the github UI or the `hub release` command to actually make the release? It's weird quirk that creating the tag makes it show up on the release page but it's not actually considered a "release". Also, for future reference you can use https://github.com/Vector35/release_helper which automates the process (though it's still very beta)

**Comment by EliseZeroTwo** [comment]
I did already do this, did I not do it correctly?

**Comment by psifertex** [comment]
Nevermind, I typoed something. 😛

**Comment by psifertex** [comment]
Rather, for the next release, please remove the `v` from the tag if you don't mind, our original examples/documentation used it but we realized afterward that was a bad idea. :-) 

Done!

**Comment by EliseZeroTwo** [comment]
Sure. You might want to update the readme of this repo as it is what I followed.

**Comment by psifertex** [comment]
Oh, thanks! I updated it a few other places but missed that one. Fixed.
