### ISSUE TITLE
[NewPlugin]  toolCHAINZ hexfiles 1.0.0

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/community-plugins#116]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: hexfiles
Release: https://github.com/toolCHAINZ/hexfiles/releases/tag/1.0.0

**Comment by psifertex** [comment]
Ohh, nice! I had an intel hex loader that I never got around to publishing, thanks for releasing this. Added.
