### ISSUE TITLE
[NewPlugin]  Ben Pottier - CryptoScan - v1.0

### ISSUE THREAD

**Issue by Rami114** [Vector35/community-plugins#118]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

Created release v1.0 just now. 

Author: Ben Pottier
Repo name: https://github.com/Rami114/cryptoscan/
Release: v1.0

**Comment by psifertex** [comment]
Thanks! Added.

For future updates, could you please use release names like `1.1` instead of `v1.1`? Our original documentation included a mix of some with and some without the `v` and we're trying to standardize on not having it in the future.
