### ISSUE TITLE
[NewPlugin]  uafio BinaryNinja-CHIP8-Arch v1.0

### ISSUE THREAD

**Issue by uafio** [Vector35/community-plugins#119]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: uafio
Repo name: BinaryNinja-CHIP8-Arch
Release: v1.0

**Comment by psifertex** [comment]
Looks great, thanks! Two minors comments for whenever you do the next update:
1) We're trying to not use `v` in the Release names anymore just for consistency's sake though I realize we had bad documentation at the beginning that was inconsistent ourselves!
2) If you rewrite the plugin longdescription to basically be the same as the current README.md contents (except rewriting image urls like https://github.com/Vector35/snippets/blob/master/plugin.json#L1 (search for "gif") does, that will make your plugin preview in the plugin manager in BN also show images.

**Comment by uafio** [comment]
Thanks!
Did all the updates. Do I need to create a new issue for the update?

**Comment by psifertex** [comment]
Thanks! Just let me know the new release name and I'll generate it. In the future, a new issue is probably best but either works. :-)

**Comment by uafio** [comment]
1.0
https://github.com/uafio/BinaryNinja-CHIP8-Arch/releases/tag/1.0
Thanks

**Comment by psifertex** [comment]
Hah, I just went and looked and am updating now. 👍

**Comment by psifertex** [comment]
Looks great in the plugin manager with the animation, btw.
