### ISSUE TITLE
new submission: binjago

### ISSUE THREAD

**Issue by zznop** [Vector35/community-plugins#12]
I've been writing a plugin that to assist with CTF's (and other general static analysis tasks) that I figure I'd submit in hope that it can also help someone else. It's more of a suite of plugins that I use personally, but may also be useful to others. I plan to continue to add more and more functionality as I encounter problems that I feel can be solved through static analysis using BN. Currently this plugin contains the following:
- a ROP gadget locator for x86 and x86-64 (soon to support multiple archs hopefully by using BN IL)
- a plugin that finds and applies comments on calls to certain libc/OS API functions to help enumerate function args (using BN IL)
- a plugin that finds x86 and ARM function prologues in firmware flat files. (I hope to build this out to support enumeration of many file header signatures (similar to binwalk))
- a plugin that finds direct and indirect recursion using BN IL

many more to come..

Here's the link: https://github.com/zznop/binjago

**Comment by psifertex** [comment]
I'm assuming it's pronounced like ninjago? :-P

**Comment by psifertex** [comment]
Also, looks good. Minor suggestion: maybe add the description from here into the plugin.json so there is a better description in the repo readme? I'll pull it as soon as I get my laptop out either way.

**Comment by zznop** [comment]
Yes, pronounced liked Ninjago (I Dad). And thanks, I plan on building out this framework to the point where it needs its own documentation. In the meantime though I’ll be sure to make the README more descriptive and include some screenshots.

**Comment by zznop** [comment]
Should be good to go!

**Comment by psifertex** [comment]
Thanks! Added.
