### ISSUE TITLE
[UpdatePlugin]  Daniel Weber golang-symbol-restore 1.1

### ISSUE THREAD

**Issue by d-we** [Vector35/community-plugins#120]
Please update my plugin: https://github.com/d-we/binja-golang-symbol-restore

Author: Daniel Weber
Repo name: https://github.com/d-we/binja-golang-symbol-restore
Release: Golang Symbol Restore Version 1.1

Thank you in advance! :)

**Comment by psifertex** [comment]
Updated, thanks!
