### ISSUE TITLE
[NewPlugin]  mauronz binja-emotet 0.1

### ISSUE THREAD

**Issue by mauronz** [Vector35/community-plugins#122]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: mauronz
Repo name: binja-emotet
Release: 0.1

**Comment by psifertex** [comment]
Thanks for the submission! Added.
