### ISSUE TITLE
[NewPlugin] catnip logrn 1.0.1

### ISSUE THREAD

**Issue by sum-catnip** [Vector35/community-plugins#125]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: sum-catnip
Repo name: logrn
Release: 1.0.1

**Comment by psifertex** [comment]
Thanks, added! Appreciate you getting the long_description too. :-) Makes them look so much nicer:
<img width="1286" alt="Screen Shot 2020-10-02 at 11 25 16 AM" src="https://user-images.githubusercontent.com/140215/94940764-f3b67980-04a1-11eb-9d84-4cab2ba355c9.png">

**Comment by psifertex** [comment]
Oh, one super minor note -- it looks like the plugin.json still had 1.0.0. Might I recommend: https://github.com/Vector35/release_helper for making that process a bit less tedious?

**Comment by sum-catnip** [comment]
Ah shit you're right. I'll use the release helper next time, thanks!

**Comment by psifertex** [comment]
No worries, super minor. Especially since it's the first time it's been in the plugin manager anyway.
