### ISSUE TITLE
[NewPlugin]  ImNotAVirus delphi_ninja v0.1.0

### ISSUE THREAD

**Issue by ImNotAVirus** [Vector35/community-plugins#126]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: ImNotAVirus
Repo name: [delphi_ninja](https://github.com/ImNotAVirus/delphi_ninja)
Release: v0.1.0

**Comment by psifertex** [comment]
Thanks! Added. 

For future releases if you can please omit the `v` we're trying to standardize on just the number.
