### ISSUE TITLE
[UpdatePlugin]  ImNotAVirus delphi_ninja 0.1.1

### ISSUE THREAD

**Issue by ImNotAVirus** [Vector35/community-plugins#127]
Please update my plugin:

Author: ImNotAVirus
Repo name: [delphi_ninja](https://github.com/ImNotAVirus/delphi_ninja)
Release: [https://github.com/ImNotAVirus/delphi_ninja/releases/tag/0.1.1](https://github.com/ImNotAVirus/delphi_ninja/releases/tag/0.1.1)

Updated `long_description` in plugin.json to match README and normalize version number (remove `v`)

**Comment by psifertex** [comment]
I'm so sorry I missed this update previously. My apologies. Should now be updated in the plugin manager.
