### ISSUE TITLE
New Submission: ripr

### ISSUE THREAD

**Issue by pbiernat** [Vector35/community-plugins#13]
Hey!

I modified the directory structure of ripr and added a `plugin.json` to match the binja plugin format. Let me know if there's any other changes I should make before it can be included in this list.

[Link to ripr repo](https://github.com/pbiernat/ripr)

**Comment by psifertex** [comment]
Thanks! Added.

Now the plugin can be installed via the following console script:

```mgr = RepositoryManager()
mgr.install_plugin("ripr")
mgr.enable_plugin("ripr")```
