### ISSUE TITLE
[UpdatePlugin]  borzacchiello seninja 0.2.1

### ISSUE THREAD

**Issue by borzacchiello** [Vector35/community-plugins#130]
Please update my plugin:

Author: Me
Repo name: seninja
Release: https://github.com/borzacchiello/seninja/releases/tag/0.2.1

**Comment by psifertex** [comment]
Updated, thanks. Looking forward to checking it out, looks like a nice update. Looking forward to checking it out.

**Comment by psifertex** [comment]
Oh heh, I was diff'ing to 0.1 instead of 0.2. Still need to check it out. 😉

**Comment by psifertex** [comment]
I'm curious whether the removal of the use case example was just to de-clutter or whether it no longer works that way?

**Comment by borzacchiello** [comment]
Just to de-clutter the readme! I added a video in the wiki on the flare-on example where I'm using the new functionalities :).
