### ISSUE TITLE
[UpdatePlugin]  ehntoo binaryninja-svd v2.0.0

### ISSUE THREAD

**Issue by ehntoo** [Vector35/community-plugins#131]
Please update my plugin:

Author: Me
Repo name: [binaryninja-svd](https://github.com/ehntoo/binaryninja-svd)
Release: https://github.com/ehntoo/binaryninja-svd/releases/tag/v2.0.0

SVD annotations are now persistent, and includes an awesome new SVD Browser from @psifertex

**Comment by psifertex** [comment]
\o/
(added)
