### ISSUE TITLE
[UpdatePlugin]  Daniel Weber binja-golang-symbol-restore 1.2

### ISSUE THREAD

**Issue by d-we** [Vector35/community-plugins#132]
Please update my plugin: Golang Symbol Restore

Author: Daniel Weber
Repo name: [d-we/binja-golang-symbol-restore](https://github.com/d-we/binja-golang-symbol-restore)
Release: 1.2

I merged a PR which sanitizes function names to make it easier to annotate types for the generated names in some cases

Thanks in advance!

**Comment by psifertex** [comment]
Much appreciated, updated!
