### ISSUE TITLE
[NewPlugin]  Martin Petran ghinja 1.0

### ISSUE THREAD

**Issue by Martyx00** [Vector35/community-plugins#133]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: ghinja
Release: https://github.com/Martyx00/ghinja/releases/tag/0.1

**Comment by psifertex** [comment]
Added, thanks! Looking forward to playing with it some. 

Oh, one note -- you'll want to change the way you're including images for future releases. Unfortunately if you use the readme image relative path it won't work in the pluginmanager: 

<img width="1531" alt="Screen Shot 2020-10-20 at 9 13 21 PM" src="https://user-images.githubusercontent.com/140215/96661001-160d1b80-1319-11eb-8b99-7c9dc346a3ee.png">

Instead, you'll want to do something like linking to the raw=true form as shown in: https://github.com/Vector35/debugger/blob/master/plugin.json#L12
