### ISSUE TITLE
[NewPlugin]  travisgoodspeed symgrate2-binja-plugin 1.3.3

### ISSUE THREAD

**Issue by travisgoodspeed** [Vector35/community-plugins#146]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Travis Goodspeed
Repo name: symgrate2-binja-plugin
Release: 1.3.3

Real release log follows.

```
dell% git tag -a 1.3.3
dell% git push origin 1.3.3
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 174 bytes | 174.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:travisgoodspeed/symgrate2-binja-plugin.git
 * [new tag]         1.3.3 -> 1.3.3
dell% hub release create 1.3.3
https://github.com/travisgoodspeed/symgrate2-binja-plugin/releases/tag/1.3.3
dell% 
```

**Comment by psifertex** [comment]
Much appreciated. Added, should already be available in the BN plugin manager.
