### ISSUE TITLE
[NewPlugin]  Linus S. (aka PistonMiner) binaryninja-bindiff-viewer 1.0

### ISSUE THREAD

**Issue by PistonMiner** [Vector35/community-plugins#150]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Linus S. (aka PistonMiner)
Repo name: binaryninja-bindiff-viewer
Release: 1.0

**Comment by psifertex** [comment]
Oh, neat. Thanks!

Some screenshots in the plugin.json / readme would be great as well, I'm sure people will be interested in this one!

**Comment by PistonMiner** [comment]
Thanks, good idea on the screenshots, I'll do that!
