### ISSUE TITLE
[NewPlugin]  inspier BinjaRustDemangler 0.1.0

### ISSUE THREAD

**Issue by inspier** [Vector35/community-plugins#154]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: inspier
Repo name: [BinjaRustDemangler](https://github.com/inspier/BinjaRustDemangler)
Release: 0.1.0

**Comment by psifertex** [comment]
Thanks! Added.
