### ISSUE TITLE
[UpdatePlugin]  matteyeux seprom-loader 1.0.2

### ISSUE THREAD

**Issue by matteyeux** [Vector35/community-plugins#157]
Please update my plugin:

Author: Me
Repo name: seprom-loader
Release: https://github.com/matteyeux/seprom-loader/releases/tag/1.0.2

**Comment by psifertex** [comment]
Should I not add it? Is another PR coming soon?

**Comment by matteyeux** [comment]
Noticed that I forgot to remove some code (useless elif statement and a comment) . And I was going to open a new issue.
Here is the release in case opening a new issue is not needed : https://github.com/matteyeux/seprom-loader/releases/tag/1.0.3.

**Comment by psifertex** [comment]
New issue not needed, i'll add it now, thanks.
