### ISSUE TITLE
[UpdatePlugin]  inspier BinjaRustDemangler 0.1.2

### ISSUE THREAD

**Issue by inspier** [Vector35/community-plugins#158]
Please update my plugin:

Author: inspier
Repo name: ![BinjaRustDemangler](https://github.com/inspier/BinjaRustDemangler)
Release: 0.1.2

**Comment by inspier** [comment]
Sorry just fixes the image in the `longdescription` field.

**Comment by psifertex** [comment]
Added this a while ago but forgot to close the issue. Done!
