### ISSUE TITLE
[UpdatePlugin] uni-due-syssec bn-riscv v0.2

### ISSUE THREAD

**Issue by f0rki** [Vector35/community-plugins#160]
Please update my plugin: [uni-due-syssec/bn-rsicv](https://github.com/uni-due-syssec/bn-riscv)

Author: uni-due-syssec
Repo name: bn-riscv
Release: v0.2

**Comment by psifertex** [comment]
Thanks! If you don't mind on the next release, please remove the `v` from the release tag. I know our original documentation was inconsistent, but we're trying to standardize to just have the number to make sorting/comparisons a bit simpler. 

Updated.
