### ISSUE TITLE
[NewPlugin]  ZetaTwo https://github.com/ZetaTwo/binja-gameboy v1.0

### ISSUE THREAD

**Issue by ZetaTwo** [Vector35/community-plugins#161]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: ZetaTwo
Repo name: https://github.com/ZetaTwo/binja-gameboy
Release: v1.0

**Comment by psifertex** [comment]
D'oh, sorry I missed this before. Added to the plugin manager.
