### ISSUE TITLE
[NewPlugin]  Ayrx binja-JNIAnalyzer v0.1

### ISSUE THREAD

**Issue by Ayrx** [Vector35/community-plugins#162]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Ayrx
Repo name: https://github.com/Ayrx/binja-JNIAnalyzer
Release: v0.1 (https://github.com/Ayrx/binja-JNIAnalyzer/releases/tag/v0.1)

**Comment by psifertex** [comment]
Added, thanks! Sorry for the delay. Note that for future releases, we recommend using a release version like "0.1" instead of "v0.1".
