### ISSUE TITLE
[NewPlugin] TUBerlin fgsect/JMPscare-binja 1.0

### ISSUE THREAD

**Issue by pr0me** [Vector35/community-plugins#163]
Please add our plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Dominik Maier, Lukas Seidel
Repo name: fgsect/JMPscare-binja
Release: 1.0

https://github.com/fgsect/JMPscare-binja

**Comment by psifertex** [comment]
Added, thanks!
