### ISSUE TITLE
[UpdatePlugin]  sum-catnip logrn 1.0.2

### ISSUE THREAD

**Issue by sum-catnip** [Vector35/community-plugins#164]
Please update my plugin: https://github.com/sum-catnip/logrn

Author: sum-catnip
Repo name: logrn
Release: 1.0.2

**Comment by psifertex** [comment]
Good news, we no longer require plugin updates for your plugin to file issues. We are tracking all added plugins and whenever we see a release we will automatically update it for you in the plugin manager. (You can see the auto update property in the listing.json). If you'd like us to switch you back to manual releases, just let us know.
