### ISSUE TITLE
[NewPlugin] jonpalmisc/screenshot_ninja @ v1.3.1

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/community-plugins#165]
Author: `jonpalmisc`
Repo name: `screenshot_ninja`
Release: `Version 1.3.1` (tag `v1.3.1`)

### Links

Repo link: https://github.com/jonpalmisc/screenshot_ninja
Release link: https://github.com/jonpalmisc/screenshot_ninja/releases/tag/v1.3.1

**Comment by psifertex** [comment]
Added, thanks.
