### ISSUE TITLE
[NewPlugin]  amtal microblaze 0.0.1

### ISSUE THREAD

**Issue by amtal** [Vector35/community-plugins#167]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: [microblaze](https://github.com/amtal/microblaze)
Release: [0.0.1](https://github.com/amtal/microblaze/releases/tag/0.0.1)

**Comment by psifertex** [comment]
Added, thanks! Looks like a well-done plugin. How's the lifting/HLIL looking?
