### ISSUE TITLE
[NewPlugin]  Linus S. (aka PistonMiner) binaryninja-gc-load-map v1.0.0

### ISSUE THREAD

**Issue by PistonMiner** [Vector35/community-plugins#169]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Linus S. (aka PistonMiner)
Repo name: binaryninja-gc-load-map
Release: v1.0.0

**Comment by psifertex** [comment]
D'oh! So sorry for forgetting these two, haven't been in the habit of checking this repo lately. Added, thanks!
