### ISSUE TITLE
[NewPlugin] Zack Orndorff binja-xtensa 0.5

### ISSUE THREAD

**Issue by zackorndorff** [Vector35/community-plugins#171]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Zack Orndorff
Repo name: [binja-xtensa](https://github.com/zackorndorff/binja-xtensa)
Release: 0.5

Link to release: https://github.com/zackorndorff/binja-xtensa/releases/tag/0.5

**Comment by zackorndorff** [comment]
Heh, ninja update, I forgot to link to GitHub urls for images in my README.

Fixed in 0.5.1: https://github.com/zackorndorff/binja-xtensa/releases/tag/0.5.1

**Comment by psifertex** [comment]
Added, thanks!
