### ISSUE TITLE
[NewPlugin]  EliseZeroTwo & matteyeux iBoot-Binja-Loader v1.0.0

### ISSUE THREAD

**Issue by matteyeux** [Vector35/community-plugins#172]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: EliseZeroTwo & matteyeux
Repo name: [iBoot-Binja-Loader](https://github.com/EliseZeroTwo/iBoot-Binja-Loader)
Release: [v1.0.0](https://github.com/EliseZeroTwo/iBoot-Binja-Loader/releases/tag/v1.0.0)

**Comment by psifertex** [comment]
Added, thanks!
