### ISSUE TITLE
Update plugin Request - Ghinja

### ISSUE THREAD

**Issue by Martyx00** [Vector35/community-plugins#174]
I would like to ask for an update of my plugin Ghinja with the new release:
https://github.com/Martyx00/ghinja/releases/tag/1.7 

PS: not sure if this is s till the way to request this :)

**Comment by psifertex** [comment]
No need to request it at all anymore! We now automatically track and then manually update each plugin on our side. I'll push the update first thing tomorrow.

**Comment by Martyx00** [comment]
That sounds amazing :) Closing the issue.
