### ISSUE TITLE
[NewPlugin] matteyeux binja-import-header v1.0.0

### ISSUE THREAD

**Issue by matteyeux** [Vector35/community-plugins#176]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Hopefully we have some [equivalent feature](https://github.com/Vector35/binaryninja-api/issues/1949) fully integrated in Binja UI one day :)   

Author: matteyeux
Repo name: [binja-import-header](https://github.com/matteyeux/binja-import-header)
Release: [v1.0.0](https://github.com/matteyeux/binja-import-header/releases/tag/v1.0.0)

**Comment by psifertex** [comment]
Thanks for the plugin submission! I've got a similar feature on a stash that includes some other bits like optional recursive loading but this is a good reminder I need to finish it up. I'll either lane that on dev later today or add this plugin one of the two. :-)

**Comment by matteyeux** [comment]
Hey Jordan !

If you have something better and native to binja than this very basic plugin, the issue can be closed.

**Comment by psifertex** [comment]
Sorry for the delay on the first party feature -- I went ahead and added this plugin in the meantime and will remove it once I can finish up my original plans.

**Comment by matteyeux** [comment]
Thank you. Looking forward the native version :D
