### ISSUE TITLE
[NewPlugin]  binja-il-hierarchy v1.2

### ISSUE THREAD

**Issue by fabianfreyer** [Vector35/community-plugins#177]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: https://github.com/fabianfreyer/binja-il-hierarchy
Release: 1.2

**Comment by psifertex** [comment]
What a great plugin idea! we should have done that natively. 

Unfortunately though the plugin.json is invalid:
remove spurious comma: https://github.com/fabianfreyer/binja-il-hierarchy/blob/main/plugin.json#L28
and escape the quotes in the license please: https://github.com/fabianfreyer/binja-il-hierarchy/blob/main/plugin.json#L15

**Comment by fabianfreyer** [comment]
Should be fixed. FWIW, the quotes in the license were put there by the "export to plugin" feature in snippets

**Comment by psifertex** [comment]
Oh! Thanks, that's good to know. I'll fix that upstream. 

Uhh, let me fix that first since there's more escaped quotes that were missed in that release. :-(

**Comment by psifertex** [comment]
Generator should be fixed fwiw if you pull the latest snippets. Sorry about that!

**Comment by psifertex** [comment]
*ping* Any chance for an update so I can add to the plugin manager? Been working quite nicely as a manual install

**Comment by psifertex** [comment]
Oh! Nevermind, I totally missed it was fixed already. Sorry about that. :-) 

Adding now.
