### ISSUE TITLE
[NewPlugin]  EliseZeroTwo SEH-Helper v0.1.0

### ISSUE THREAD

**Issue by EliseZeroTwo** [Vector35/community-plugins#178]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: EliseZeroTwo
Repo name: SEH-Helper
Release: v0.1.0

**Comment by psifertex** [comment]
added, thanks!
