### ISSUE TITLE
[NewPlugin]  b0bb 0CD 0.1

### ISSUE THREAD

**Issue by 0xb0bb** [Vector35/community-plugins#179]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I used the `hub` command to create a _real_ release.

Author: b0bb
Repo name: [0CD](https://github.com/0xb0bb/0CD)
Release: [0.1](https://github.com/0xb0bb/0CD/releases/tag/0.1)

**Comment by psifertex** [comment]
This was added some time ago, sorry for not closing the issue.
