### ISSUE TITLE
[UpdatePlugin] ImNotAVirus delphi_ninja 0.1.2

### ISSUE THREAD

**Issue by ImNotAVirus** [Vector35/community-plugins#181]
Due to a bad manipulation, my releases were in Draft. It should be fixed now.

Author: ImNotAVirus
Repo name: [delphi_ninja](https://github.com/ImNotAVirus/delphi_ninja)
Release: https://github.com/ImNotAVirus/delphi_ninja/releases/tag/0.1.2

**Comment by psifertex** [comment]
Added a while ago but looks like I forgot to close this issue.
