### ISSUE TITLE
[NewPlugin]  CyShell ClassyPP 1.0

### ISSUE THREAD

**Issue by CySHell** [Vector35/community-plugins#183]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: CyShell
Repo name: [ClassyPP](https://github.com/CySHell/ClassyPP)
Release: [1.0](https://github.com/CySHell/ClassyPP/releases/tag/1.0)

**Comment by psifertex** [comment]
Please update it after fixing the `minimumbinaryninjaversion` which is not currently a valid json value. It should just be `3233`. You can verify your plugin.json is valid by:

```python -m json.tool < plugin.json``` and verifying it parses.

**Comment by CySHell** [comment]
Done

**Comment by CySHell** [comment]
Done :)

**Comment by psifertex** [comment]
Added, thanks!
