### ISSUE TITLE
[NewPlugin]  CyShell ClassyPP 1.1

### ISSUE THREAD

**Issue by CySHell** [Vector35/community-plugins#184]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag.

I either used the UI, or the hub command to create a real release.

Author: CyShell
Repo name: [ClassyPP](https://github.com/CySHell/ClassyPP)
Release: [1.1](https://github.com/CySHell/ClassyPP/releases/tag/1.1)

**Comment by psifertex** [comment]
Thanks! No need to file issues for updates though going forward, we get automatic notifications for any releases and will update it after manual review. 

I'm on vacation so a bit slower than normal this week but I was hopping on for some other things this morning so it's updated. :-)
