### ISSUE TITLE
[NewPlugin]  Galen Williamson binaryninja-m68k 0.5

### ISSUE THREAD

**Issue by galenbwill** [Vector35/community-plugins#185]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

This plugin supersedes the version previously maintained by @wrigjl, last updated in #155 

Author: Galen Williamson
Repo name: [binaryninja-m68k](https://github.com/galenbwill/binaryninja-m68k)
Release: [0.5](https://github.com/galenbwill/binaryninja-m68k/releases/tag/0.5)

**Comment by psifertex** [comment]
Did this a while ago but forgot to close.
