### ISSUE TITLE
[NewPlugin]  tizmd binja-v850 0.1.1

### ISSUE THREAD

**Issue by tizmd** [Vector35/community-plugins#186]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: tizmd
Repo name: [binja-v850](https://github.com/tizmd/binja-v850.git)
Release: [0.1.1](https://github.com/tizmd/binja-v850/releases/tag/0.1.1)

**Comment by psifertex** [comment]
Added, thanks! 

One suggestion that makes it easier to test -- if there's a small example file that you can use to validate it and test it, that's helpful for us as well when making sure everything's still working in the future.
