### ISSUE TITLE
[NewPlugin]  pbiernat ripr 1.1.1

### ISSUE THREAD

**Issue by pbiernat** [Vector35/community-plugins#187]
Please add my plugin to the repository. Sorry for the extremely "quick" turnaround ;)

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: pbiernat
Repo name: [ripr](https://github.com/pbiernat/ripr)
Release:[1.1.1](https://github.com/pbiernat/ripr/releases/tag/1.1.1)

**Comment by psifertex** [comment]
Awesome! Really looking forward to using it again, had use for ripr not that long ago, was halfway to updating it myself. :-) Added.
