### ISSUE TITLE
[NewPlugin]  LittleDyingDuck BinaryNinja-RichPrecense plugin

### ISSUE THREAD

**Issue by LittleDyingDuck** [Vector35/community-plugins#191]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: BinaryNinja-RichPrecense
Release: 1.0

**Comment by CouleeApps** [comment]
Hiya, please [make a release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) on your plugin's GitHub repo.

**Comment by LittleDyingDuck** [comment]
> Hiya, please [make a release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) on your plugin's GitHub repo.

If you mean [this](https://github.com/LittleDyingDuck/BinaryNinja-RichPrecense/releases/tag/release), then there ya go.

**Comment by CouleeApps** [comment]
Yep, looks good. Thanks for the plug-in!
