### ISSUE TITLE
[NewPlugin]  seeinglogic ariadne 0.1.0

### ISSUE THREAD

**Issue by seeinglogic** [Vector35/community-plugins#193]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ [release](https://github.com/seeinglogic/ariadne/releases/tag/0.1.0).

Author: Mark Griffin (@seeinglogic)
Repo name:ariadne
Release: 0.1.0

**Comment by psifertex** [comment]
Thanks for the submission, sorry for the delay. What a fun plugin, really looking forward to checking it out on stream and publicizing it.
