### ISSUE TITLE
[UpdatePlugin]  tizmd binja-v850 0.1.2

### ISSUE THREAD

**Issue by tizmd** [Vector35/community-plugins#195]
I added a code example and fixed a little including typos.

Author: tizmd
Repo name: [binja-v850](https://github.com/tizmd/binja-v850.git)
Release:  [0.1.2](https://github.com/tizmd/binja-v850/releases/tag/0.1.2)

**Comment by psifertex** [comment]
Thanks! Update running now. Just as an FYI -- we actually see your releases automatically now in our slack channel and we'll automatically trigger a plugin manager update when we do so you don't even have to file this issue request anymore. :-)

**Comment by psifertex** [comment]
(for updates that is, for new plugins, definitely let us know still)
