### ISSUE TITLE
[NewPlugin] skr0x1c0 ipybinja 0.2.5

### ISSUE THREAD

**Issue by skr0x1c0** [Vector35/community-plugins#196]
Please add my plugin to the repository.

Repo: [https://github.com/skr0x1c0/ipybinja](url)

Author: skr0x1c0
Repo name: ipybinja
Release: 0.2.5

**Comment by psifertex** [comment]
Sorry for the delay in responding here -- there's no actual releases created here, you can't just make a tag but have to do an actual release:

https://github.com/skr0x1c0/ipybinja/releases

More details: https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release

Though I recommend using: https://github.com/Vector35/release_helper which can simplify the process

**Comment by skr0x1c0** [comment]
Sorry about that. Created a new release 0.2.5

**Comment by psifertex** [comment]
Appreciate the quick turn around, thanks.

**Comment by skr0x1c0** [comment]
@psifertex When will you be re-releasing this plugin?

**Comment by psifertex** [comment]
Oh, sorry, it already updated I just forgot to re-close the issue. It's live in the plugin manager and I was using it a few days ago!
