### ISSUE TITLE
[UpdatePlugin] TUBerlin fgsect/JMPscare-binja 1.1

### ISSUE THREAD

**Issue by pr0me** [Vector35/community-plugins#198]
Please update my "JMPscare" plugin to 1.1.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Lukas Seidel
Repo name: fgsect/JMPscare-binja
Release: v1.1

https://github.com/fgsect/JMPscare-binja/

**Comment by psifertex** [comment]
Done! Should be live shortly. 

Also, you don't actually have to let us know anymore with an issue. 

We automatically monitor all new releases and trigger the update ourselves without you having to file anything. If we miss an update after a few days though feel free to file anyway if you like. :-)
