### ISSUE TITLE
[NewPlugin]  WhatTheFuzz binaryninja-openai 1.0.0

### ISSUE THREAD

**Issue by WhatTheFuzz** [Vector35/community-plugins#199]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Sean Deaton (@WhatTheFuzz)
Repo name: [binaryninja-openai](https://github.com/WhatTheFuzz/binaryninja-openai)
Release: [Initial Release](https://github.com/WhatTheFuzz/binaryninja-openai/releases/tag/1.0.0)

**Comment by psifertex** [comment]
Looks great, I'll add it shortly. Can I also suggest that maybe allowing people to use the settings system to put their openai key in would be useful?

**Comment by psifertex** [comment]
Added, thanks!

Also, few other notes:

Are you aware of https://github.com/mahaloz/DAILA

Secondly, you might consider removing the `longdescription` from your plugin.json. The newer plugin manager behavior is to just render the readme directly in that case which makes it easier to maintain. Though you do have to format the images in the readme [a bit differently](https://github.com/Vector35/snippets/blame/master/README.md#L12) to have them render in a compatible way.

**Comment by WhatTheFuzz** [comment]
Registering keys in Settings was super easy and implemented in [218a681](https://github.com/WhatTheFuzz/binaryninja-openai/commit/218a681a79a808fc117700b68c76b23d62669f19). I will cut a new release later today. Thanks Jordan.
