### ISSUE TITLE
new plugin

### ISSUE THREAD

**Issue by pmackinlay** [Vector35/community-plugins#20]
I've developed an initial plugin for the CLIPPER CPU and two associated binary views. While I don't think there's much interest in such an obsolete system generally, I guess it doesn't hurt to share it with others.

The repository is here: [binaryninja-clipper](https://github.com/pmackinlay/binaryninja-clipper).

**Comment by wayframer** [comment]
I propose a pr to add your plugin in the list

**Comment by psifertex** [comment]
Thanks for the reminder, I'd missed this one. Added.
