### ISSUE TITLE
[NewPlugin]  AsherDLL AsherDLL/PCDump-bn v1.0

### ISSUE THREAD

**Issue by AsherDLL** [Vector35/community-plugins#200]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Asher Davila L.
Repo name: AsherDLL/PCDump-bn (https://github.com/AsherDLL/PCDump-bn)
Release: PCDump v1.0 (https://github.com/AsherDLL/PCDump-bn/releases/tag/v1.0)

**Comment by psifertex** [comment]
Thanks, added.

For what it's worth, some of this is approximated by just switching to linear view / pseudoc and disabling addresses and using the "File" / "Export" / "Linear View" menu option, but they have slightly different behaviors and I can see someone preferring this style. Plus this can be configured to be more flexible such as a single function, etc.
