### ISSUE TITLE
[NewPlugin]  Jacopo Ferrigno golang_pclntab_parser 1.1

### ISSUE THREAD

**Issue by dipusone** [Vector35/community-plugins#202]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Jacopo Ferrigno
Repo name: [golang_pclntab_parser](https://github.com/dipusone/golang_pclntab_parser)
Release: [GoLang binary parser v1.1](https://github.com/dipusone/golang_pclntab_parser/releases/tag/1.1)

**Comment by psifertex** [comment]
Thanks for the quick update -- just as a heads up though, no need to notify us for future releases via an issue. We're automatically tracking all changes and will update in the plugin manager on our own after review so you just need to trigger the release and nothing else!
