### ISSUE TITLE
[NewPlugin] elbee analyze_char_arrays v1.0

### ISSUE THREAD

**Issue by elbee-cyber** [Vector35/community-plugins#204]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: elbee
Repo name: https://github.com/elbee-cyber/analyze_char_arrays
Release: https://github.com/elbee-cyber/analyze_char_arrays/releases/tag/1.0

**Comment by psifertex** [comment]
Assuming the automation works this should be live in a few minutes in the plugin manager. Thanks! Hopefully the plugin won't be needed when https://github.com/Vector35/binaryninja-api/issues/1637 lands but appreciate it until then!

**Comment by elbee-cyber** [comment]
I don't think the automation worked, some friends tried to install for a CTF and it's not appearing on the plugin manager nor is it available on my copy's plugin manager. Looked at the commits and noticed that the most recent plugin added besides mine also isn't appearing

**Comment by psifertex** [comment]
You didn't change the name from the sample plugin so unfortunately it's a name collision with the "sample plugin". I see you fixed it after the release but you need to generate a new release before it will pull the correct plugin.json information.

**Comment by psifertex** [comment]
The second most recent added plugin is correctly available afaict. 

<img width="1392" alt="Screenshot 2023-01-18 at 4 27 35 PM" src="https://user-images.githubusercontent.com/140215/213298682-aaf61e33-8ccf-490c-8133-6bb1dc9a81f5.png">

**Comment by elbee-cyber** [comment]
Sorry about that I'm honestly not too good with git, I created a new release. I also created a new tag, but I'm not sure if that was necessary

**Comment by psifertex** [comment]
No worries, you got it the second time, thanks. You might find the update/release process easier if you using [release_helper](https://github.com/Vector35/release_helper). I wrote that specifically because I didn't want to mess with all the steps myself. 😉

**Comment by psifertex** [comment]
Also, for future updates, we're tracking the plugin automatically and will notice the release and trigger the update on our side after review, no issue necessary.
