### ISSUE TITLE
[NewPlugin] cxiao HashDB v1.0.0

### ISSUE THREAD

**Issue by cxiao** [Vector35/community-plugins#205]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Cindy Xiao
Repo name: [cxiao/hashdb_bn](https://github.com/cxiao/hashdb_bn)
Release: [v1.0.0](https://github.com/cxiao/hashdb_bn/releases/tag/v1.0.0)

Finally sat down and tagged this plugin for release :) Thanks again @psifertex for the initial implementation, it was really really useful to have something already there to hack on!

**Comment by psifertex** [comment]
Added yesterday, thanks for the high quality plugin!
