### ISSUE TITLE
[NewPlugin]  dayzerosec dayzerosec/AMD-SP-Loader v1.0

### ISSUE THREAD

**Issue by Cryptogenic** [Vector35/community-plugins#206]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: dayzerosec
Repo name: [dayzerosec/AMD-SP-Loader](https://github.com/dayzerosec/AMD-SP-Loader)
Release: [v1.0](https://github.com/dayzerosec/AMD-SP-Loader/releases/tag/v1.0)

**Comment by psifertex** [comment]
Added this a little while back and forgot to close the issue, sorry for the delay, thanks for submitting the plugin!
