### ISSUE TITLE
[UpdatePlugin]  apekros binja_sigmaker 2.1

### ISSUE THREAD

**Issue by greaka** [Vector35/community-plugins#208]
I am not the creator, but this plugin had an update.

However, `listing.json` does not have `auto_update` set to true for this plugin. Could this please be changed?

**Comment by psifertex** [comment]
No problem, thanks for letting me know.  Usually that's because the plugin was the old-style plugin format, but it should be good to migrate.

**Comment by psifertex** [comment]
Should now be updated in the plugin manager.
