### ISSUE TITLE
support for maximum version

### ISSUE THREAD

**Issue by psifertex** [Vector35/community-plugins#211]
When building a python plugin that loads/installs a native plugin, it would be great if there was support for maximum version. This would, for example, make it obvious before installing a plugin that it wasn't compatible with dev.

**Comment by psifertex** [comment]
We should also add support for a full semver comparison instead of _just_ the build.

**Comment by 0xdevalias** [comment]
> Closing this here as we're tracking this as a part of our migration to the new extension manager and updated plugin manager

@psifertex Is there another public issue for that that you can link to? And/or a potential timeline?

**Comment by psifertex** [comment]
It's technically already supported but only for official plugins. At this point keep an eye out on the blog which is where we'll be releasing information on the new system when it's available. I expect it in the "G" release.

**Comment by 0xdevalias** [comment]
@psifertex Cool, thanks for the info :)
