### ISSUE TITLE
[NewPlugin] rikodot binja_native_sigscan_loader 1.0.2

### ISSUE THREAD

**Issue by rikodot** [Vector35/community-plugins#212]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: [binja_native_sigscan_loader](https://github.com/rikodot/binja_native_sigscan_loader)
Release: [Native SigScan Loader 1.0.2](https://github.com/rikodot/binja_native_sigscan_loader/releases/tag/1.0.2)

**Comment by psifertex** [comment]
Thanks for the update! No need to let us know of updates in the future -- we actually track all plugins automatically and will update them in the plugin manager when we see releases after we review them. If you ever notice we're a few days behind feel free to file an issue but you shouldn't even have to do that! Should be live shortly.
