### ISSUE TITLE
[Binja-Rpyc]  hugsy binja-headless v0.1

### ISSUE THREAD

**Issue by hugsy** [Vector35/community-plugins#213]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: hugsy
Repo name: binja-headless
Release: v0.1
Link: https://github.com/hugsy/binja-headless/releases/tag/v0.1

**Comment by psifertex** [comment]
Unfortunately after some internal discussion we are not going to accept this plugin to the plugin manager. The lack of headless in non-commercial is a license distinction and while we don't plan to plugins such as this, we also aren't going to encourage their use either.
