### ISSUE TITLE
[copy-as-yara]  ald3ns copy-as-yara v1.0

### ISSUE THREAD

**Issue by ald3ns** [Vector35/community-plugins#215]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://github.com/ald3ns/copy-as-yara/releases/tag/1.0) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: ald3ns
Repo name: [copy-as-yara](https://github.com/ald3ns/copy-as-yara/releases/tag/1.0)
Release: 1.0

**Comment by psifertex** [comment]
Added, thanks!
