### ISSUE TITLE
[NewPlugin] cxiao rust_type_layout_helper_bn v1.0.0

### ISSUE THREAD

**Issue by cxiao** [Vector35/community-plugins#216]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Cindy Xiao
Repo name: [cxiao/rust_type_layout_helper_bn](https://github.com/cxiao/rust_type_layout_helper_bn)
Release: [v1.0.0](https://github.com/cxiao/rust_type_layout_helper_bn/releases/tag/v1.0.0)

Hi, I wrote a small plugin to import some type information emitted by the Rust compiler (when passed a certain flag) into Binary Ninja. Let me know if there need to be any changes before getting this into the community plugins repo!

**Comment by psifertex** [comment]
added, thanks!
