### ISSUE TITLE
Update of hexfiles to 1.1.0

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/community-plugins#217]
Please update hexfiles to 1.1.0.

**Comment by psifertex** [comment]
no need to let us know, we track all releases automatically, thanks!

**Comment by psifertex** [comment]
Also, added to the repro... :-)

**Comment by toolCHAINZ** [comment]
lol thanks! I was wondering what I could have read that told me to make an issue and realized that it was the [very old plugin manager blog post](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#6-submitting-your-plugin) 😆

**Comment by psifertex** [comment]
No worries, I really need to edit that! The submission process is the same, but updates are changed.
