### ISSUE TITLE
[NewPlugin]  saagarjha binja-swift-demangler v1.0

### ISSUE THREAD

**Issue by saagarjha** [Vector35/community-plugins#218]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: @saagarjha
Repo name: [binja-swift-demangler](https://github.com/saagarjha/binja-swift-demangler)
Release: [v1.0](https://github.com/saagarjha/binja-swift-demangler/releases/tag/v1.0)

**Comment by psifertex** [comment]
Added, thanks!
