### ISSUE TITLE
[NewPlugin]  cxiao rust_string_slicer v1.0.0

### ISSUE THREAD

**Issue by cxiao** [Vector35/community-plugins#219]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Cindy Xiao
Repo name: [rust_string_slicer](https://github.com/cxiao/rust_string_slicer/)
Release: [v1.0.0](https://github.com/cxiao/rust_string_slicer/releases/tag/v1.0.0)

Hello! I've got another Rust-related Binja plugin I've been experimenting with, it's at a state where it may be useful to others, so submitting it to the plugin repo!

**Comment by psifertex** [comment]
Added, thanks!
