### ISSUE TITLE
[NewPlugin]  xclusivor binaryninja-xbe 1.0

### ISSUE THREAD

**Issue by xclusivor** [Vector35/community-plugins#220]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: [binaryninja-xbe](https://github.com/xclusivor/binaryninja-xbe)
Release: [1.0](https://github.com/xclusivor/binaryninja-xbe/releases/tag/1.0)

**Comment by psifertex** [comment]
Thanks! Sorry for not closing the issue already. :-)
