### ISSUE TITLE
[NewPlugin]  moval0x1 BinjaExportTox64dbg v1.0.0

### ISSUE THREAD

**Issue by moval0x1** [Vector35/community-plugins#222]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: moval0x1
Repo name: https://github.com/moval0x1/BinjaExportTox64dbg
Release: https://github.com/moval0x1/BinjaExportTox64dbg/releases/tag/1.0.0

**Comment by psifertex** [comment]
Added now.

**Comment by psifertex** [comment]
Looks like the import failed. I think your release name and your plugin version in the plugin.json aren't consistent. Consider maybe using https://github.com/Vector35/release_helper which can automate that process for you?

**Comment by psifertex** [comment]
Scratch that, there's some busted json in there:

```
python3 -mjson.tool < plugin.json
Expecting ',' delimiter: line 18 column 180 (char 505)
```

**Comment by moval0x1** [comment]
I've updated it; now I guess it will work. :D

**Comment by moval0x1** [comment]
Btw, the problem was in the plugin.json when I generated it was broken in some parts with " I just skipped it \".

**Comment by psifertex** [comment]
Thanks, added!
