### ISSUE TITLE
[NewPlugin]  moval0x1 CommentsAndSymbols v1.0.0

### ISSUE THREAD

**Issue by moval0x1** [Vector35/community-plugins#223]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: moval0x1
Repo name: https://github.com/moval0x1/CommentsAndSymbols
Release: https://github.com/moval0x1/CommentsAndSymbols/releases/tag/1.0.0

**Comment by psifertex** [comment]
Added now, thanks! 

The plugin could use a bit more documentation though. :-) 

Would love to see an explanation of whether it's auto->user changes, only those that happen while the plugin is installed, etc.

**Comment by psifertex** [comment]
Looks like the import failed. I think your release name and your plugin version in the plugin.json aren't consistent. Consider maybe using https://github.com/Vector35/release_helper which can automate that process for you?

**Comment by psifertex** [comment]
Scratch that, there's some busted json in there:

```
python3 -mjson.tool < plugin.json
Expecting ',' delimiter: line 18 column 180 (char 505)
```

**Comment by moval0x1** [comment]
Updated! It was the same error here in the plugin.json.

**Comment by psifertex** [comment]
Added, thanks!
