### ISSUE TITLE
support sub-folders

### ISSUE THREAD

**Issue by psifertex** [Vector35/community-plugins#23]
It's not always convenient to have the `plugin.json` or `__init__.py` to the root of the repository, so we should support some other mechanism, possibly just looking one level deep for those files.

**Comment by ekilmer** [comment]
Hello, is this being prioritized at all?

Is there anything I can do to help? 

I am thinking it might be good (for consistency) to follow what Pip uses already with the `subdirectory` component in a [VCS installation](https://pip.pypa.io/en/stable/cli/pip_install/#vcs-support).

If this feature was implemented, then plugins could follow standard Python packaging directory structure for nicer testing, project configurations, etc.

It would be fine to have the `plugin.json` file in the same directory as the actual Python module (next to `__init__.py`).

Example:
```
myplugin
├── src
|   ├── __init__.py
|   └── plugin.json
└── setup.py
```
with the listing entry as
```
{
    "name": "ekilmer/myplugin",
    "subdirectory": "src",
    "auto_update": true
}
```

**Comment by psifertex** [comment]
Thanks for the reminder -- yeah, that's basically the current plan, it's been on my todo list for a while but I was just reminded of it again for quite possibly the same reason you're inquiring. 😉 

I've got some test code I'm checking now to make sure it works. Assuming it goes well I need to have one of the other vector35 folks review it as there's a few dragons buried there but hopefully it can land soon.

**Comment by psifertex** [comment]
This is now complete! It's currently only available in recent test builds so you'll need to make sure you specify a minimum BN build version of [2920](https://github.com/psifertex/lighthouse/blob/develop/bnplugin/plugin.json#L12).

Note that that fork of lighthouse was only for testing the subfolder support and it should not be used -- an official release with that support as well as other features is in development. 

Another simple test is: https://github.com/psifertex/samplesub

The short summary is that you simply move your plugin.json and __init__.py into subfolder and we handle the rest on the [repository side](https://github.com/Vector35/community-plugins/blob/test/listing.json#L4). Just let us know what subfolder when submitting the plugin!
