### ISSUE TITLE
New submission

### ISSUE THREAD

**Issue by mozark24** [Vector35/community-plugins#24]
Small add-on which may prove useful to some as a binary property exporter to JSON to tinker with graphs.

https://github.com/mozark24/binja_JSON_Plugin

**Comment by mozark24** [comment]
No worries.  I found a few bugs and don't have time to fix them right now in this version.  I have another version working on all MLIL instruction properties but it's kind of ugly because of all the nested exception catching required.  I may post the updated version once I am sure I've worked out the kinks.

**Comment by psifertex** [comment]
Sounds good, I'll hold off adding it then.

**Comment by mozark24** [comment]
Finally got around to this again.  Definitely not the most efficient way to do it but it seems to work.

**Comment by psifertex** [comment]
Added, thanks.
