### ISSUE TITLE
[New Plugin]: Frinja - Frida plugin for binary ninja

### ISSUE THREAD

**Issue by dzervas** [Vector35/community-plugins#242]
### Plugin Description

I know that there are 2 other frida plugins already (and my plugin was forked from BinRida) but I bring a lot of new stuff to the table:

- More intuitive frida control sequence
- Much easier to mark functions for tracing (just tag the function)
- Ability to add pre/posthooks and change the return value by commenting on the function
- Frida console - just like the python one (no completion or history yet but they're coming)
- Traced function show their arguments with the correct name and type (e.g. the argument `char* my_arg` will show as `my_arg: "Hello World"` during tracing`
- Using jinja for rendering frida scripts - snippet support is coming
- Ported function context dumper from BinRida to jinja2
- Ported function paths inspect from BinRida to jinja2 - also highlights the taken paths
- Lots more to come

### Plugin Repository URL

https://github.com/dzervas/frinja

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Thanks! Since it looks like bnrida has not been maintained, I'm inclined to remove it from the plugin manager and replace it with this one.

Are there any features in https://github.com/chame1eon/binaryninja-frida/ that would make it worthwhile to keep both?

**Comment by psifertex** [comment]
Also, does the devi support mean removing https://github.com/murx-/devi_binja might be worthwhile too? I haven't used devi at all so I don't have much context for whether this plugin is a superset or not?

**Comment by dzervas** [comment]
I can't say for sure if I cover all @chame1eon's features
All of BinRida functionality has been ported and it seems unmaintained - @c3r34lk1ll3r thank you very much for you code

devi should definitely not be removed, I just use it (instead of asking manually for a json file, I feed it and call the "rest" of the plugin)

**Comment by psifertex** [comment]
Sounds good, I added it earlier and removed BinRida but just saw the other update so I'm updating it now again. Thanks! 

If you do take a look at FRIDA and it makes sense to remove it, let me know.
