### ISSUE TITLE
[New Plugin]: x64dbgbinja

### ISSUE THREAD

**Issue by utkonos** [Vector35/community-plugins#244]
### Plugin Description

# x64dbgbinja

Official x64dbg plugin for [Binary Ninja](https://binary.ninja).

## Installation

Clone this repository in your Binary Ninja plugin directory.

### Import x64dbg database

Import comments/labels from an uncompressed x64dbg JSON database in Binary Ninja.

Symbols for imported functions and or library functions can be overwritten via the "Overwrite X" entries in Settings.

### Export x64dbg database

Export comments/labels to a JSON database that can be loaded by x64dbg.

To export labels only: uncheck "Export Comments" under "x64dbg Database Export" in Settings.

### Plugin Repository URL

Repo URL: https://github.com/x64dbg/x64dbgbinja

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
added, thanks!
