### ISSUE TITLE
Type "sync" Not Appearing in Plugin Manager

### ISSUE THREAD

**Issue by utkonos** [Vector35/community-plugins#246]
The new? plugin category `sync` does not appear in the `Category` field in the Plugin Manager in BN Version 3.5.4526.

<img width="457" alt="Screenshot 2024-01-17 at 12 29 33" src="https://github.com/Vector35/community-plugins/assets/2775739/26cb3600-f6ab-451d-8551-b48b7a94b7dd">

## Additional info

The `sync` type should also be documented in the list of types at the bottom of https://github.com/Vector35/community-plugins/blob/master/README.md

Lastly, there are probably a few other (maybe more?) plugins that should have this type:
1. bninda
2. BinSync
3. ret-sync
4. revsync

**Comment by psifertex** [comment]
Reason why is that someone made up the tag and it doesn't actually exist in the UI. In general this should not be done, but that's probably worth adding. I've just added it in releases >= 4864

**Comment by psifertex** [comment]
We'll need to submit issues or PRs to those additional plugins for that category as well now that it's added.

**Comment by utkonos** [comment]
> someone made up the tag

Yes, definitely should send out a search party looking for the culprit.

https://github.com/x64dbg/x64dbgbinja/pull/1

**Comment by psifertex** [comment]
There, cross-linked all the appropriate repos. And the existing one already works as expected with the "@sync" search keyword and in the UI.
