### ISSUE TITLE
[UpdatePlugin]: movalx01 BinjaExportTox64dbg 1.0.1 

### ISSUE THREAD

**Issue by moval0x1** [Vector35/community-plugins#247]
### Plugin Description

Export notations from Binja to x64dbg

### Plugin Repository URL

Repo URL: https://github.com/moval0x1/BinjaExportTox64dbg

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Sorry about not closing this issue. This was added some time ago.
