### ISSUE TITLE
[UpdatePlugin]: movalx01 CommentsAndSymbols 1.0.2

### ISSUE THREAD

**Issue by moval0x1** [Vector35/community-plugins#252]
### Plugin Description

Show comments and symbols renamed during the analysis process.

### Plugin Repository URL

Repo URL: https://github.com/moval0x1/CommentsAndSymbols

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
No need to file these issues for new releases, we actually automatically track all plugins now and manually review and update the repo once we've done it. CI is running now, should be live shortly!
