### ISSUE TITLE
[Change plugin ownership] ZetaTwo/binja-gameboy

### ISSUE THREAD

**Issue by samrussell** [Vector35/community-plugins#253]
I've updated the ZetaTwo/binja-gameboy plugin and would like to take it over myself as I am happy to maintain it and intend to keep making improvements.

I've discussed this with @ZetaTwo on twitter: https://twitter.com/ZetaTwo/status/1762609146426273897

I've added a new tag for v1.2 and re-pushed the original v1.0 and v1.1 tags, let me know if anything is missing

**Comment by samrussell** [comment]
new repo: https://github.com/samrussell/binja-gameboy

**Comment by ZetaTwo** [comment]
Just confirming here as well that I am fine with this change.
