### ISSUE TITLE
[New Plugin]: Dixie AI VR Engineer

### ISSUE THREAD

**Issue by adriantil** [Vector35/community-plugins#257]
### Plugin Description

This plugin creates an integration between Binary Ninja and the 3Flatline Dixie Code Scanner engine. It allows a user subscribed to the Dixie Code Scanner to send functions to the server directly from the Binary Ninja platform. The engine then analyzes functions, generates a description of the code, and finds potential vulnerabilities in the decompiled code.

### Plugin Repository URL

Repo URL: https://github.com/3Flatline/DixieBinjaPlugin

### Real Release

- [X] I have made a real release

**Comment by adriantil** [comment]
Updated repo link to new, more descriptive repo name and updated the plugin to use the Sidebar scheme, which is pretty sweet tbh.

**Comment by psifertex** [comment]
Added, thanks.
