### ISSUE TITLE
Update bnida's  version

### ISSUE THREAD

**Issue by cesaryuan** [Vector35/community-plugins#258]
Describe your issue here:
[Bnida version 1.3 has been released](https://github.com/zznop/bnida/releases/tag/1.3), but the current repository is still stuck at version 1.2 and hopes to be updated.

**Comment by psifertex** [comment]
Thanks, not sure why it hasn't updated in the previous runs, it absolutely should have. I'll take a look later.

**Comment by psifertex** [comment]
Updated all zznop plugins to auto-update. 
https://github.com/Vector35/community-plugins/commit/ccb6f4da80bdcb6e230956921c6c54fd65437f5e
