### ISSUE TITLE
new plugin: mcs-48

### ISSUE THREAD

**Issue by pmackinlay** [Vector35/community-plugins#26]
I've developed an initial plugin for the Intel MCS-48 family (8021/8022/8048/8049, etc.) and a simple binary view. It works at a very basic level, although the Harvard architecture and register + memory banking require a number of ugly workarounds in BN at this point.

The repository is [here](https://github.com/pmackinlay/binaryninja-mcs48).

**Comment by psifertex** [comment]
Added, thanks.
