### ISSUE TITLE
[New Plugin]: binja-win-docs

### ISSUE THREAD

**Issue by matteyeux** [Vector35/community-plugins#260]
### Plugin Description

Binary Ninja plugin to display the documentation of a Windows function in a sidebar widget.

### Plugin Repository URL

Repo URL: https://github.com/matteyeux/binja-win-docs

### Real Release

- [X] I have made a real release

**Comment by matteyeux** [comment]
Hello,

Any update about this ? 😅

**Comment by psifertex** [comment]
Sorry about that, no idea why I was missing these notifications! Added.
