### ISSUE TITLE
[New Plugin]: FIRM-Loader

### ISSUE THREAD

**Issue by EliseZeroTwo** [Vector35/community-plugins#262]
### Plugin Description

It loads 3DS FIRM files.

### Plugin Repository URL

Repo URL: https://github.com/EliseZeroTwo/FIRM-Binja-Loader

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Thanks! Added, should be live shortly, if there's an error in adding it I'll post a note here.
