### ISSUE TITLE
[New Plugin]: RopView - Gadget Analysis Framework

### ISSUE THREAD

**Issue by elbee-cyber** [Vector35/community-plugins#264]
### Plugin Description

RopView is a gadget analysis framework capable of granular per-instruction based analysis and complex logical queries. The creation of this plugin was initially inspired by a similar, widely-used, decade-old tool in IDA called IDA Sploiter. RopView uses the unicorn cpu emulation framework to do gadget analysis and allow for semantic-based queries. Gadgets are discovered directly in the binaryview, cached and analyzed into dataframes. All the usual options exist for the gadget search in addition to analysis prestates and semantic options. See the [following blog post](https://faultpoint.com/post/2024-06-02-binja-plugin-ropview/) for technical details and explanations on what the tool does.

### Plugin Repository URL

Repo URL: https://github.com/elbee-cyber/RopView

### Real Release

- [X] I have made a real release

**Comment by CouleeApps** [comment]
Added! Nice work
