### ISSUE TITLE
[New Plugin]: Binja Doc Lookup

### ISSUE THREAD

**Issue by riskydissonance** [Vector35/community-plugins#267]
### Plugin Description

This plugin allows the user to lookup documentation online for the token under the cursor either directly in the browser (Ctrl-Q) or a summary in a tooltip (Ctrl-q).

By default it searches MSDN, and the tooltip shows the function summary and signature in the tooltip, but this is configurable in the settings.

### Plugin Repository URL

Repo URL: https://github.com/riskydissonance/binja-doc-lookup

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
added, thanks! (will take a few minutes to go live)

**Comment by psifertex** [comment]
FYI, I somehow totally missed https://github.com/Vector35/community-plugins/issues/260 which you might also be interested in! Maybe it's worth combining the two plugins together?

**Comment by 0xdevalias** [comment]
> Maybe it's worth combining the two plugins together?

That could be a cool idea! 'One BN doc viewer/helper to rule them all'. Created issues on the specific repos to raise the idea more specifically:

- https://github.com/riskydissonance/binja-doc-lookup/issues/1
- https://github.com/matteyeux/binja-win-docs/issues/2
