### ISSUE TITLE
[New Plugin]: IFL (Interactive Functions List) v1.0

### ISSUE THREAD

**Issue by leandrofroes** [Vector35/community-plugins#272]
### Plugin Description

A small plugin with the goal to provide an user-friendly way to navigate between functions, their references and informations.
Additionally, it allows the user to import reports generated by tools like [PE-sieve](https://github.com/hasherezade/pe-sieve) and [tiny_tracer](https://github.com/hasherezade/tiny_tracer) into Binary Ninja. The plugin is a Binja version of the [IDA IFL](https://github.com/hasherezade/ida_ifl) plugin written by hasherezade.

### Plugin Repository URL

Repo URL: https://github.com/leandrofroes/bn_ifl

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Added, thanks! 

Also, I know you're basing the plugin on another that chose that licenses, but fwiw, CC-BY [isn't recommended for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software). Not a huge deal, just wanted to let you know.
