### ISSUE TITLE
[New Plugin]: themida-unmutate-bn

### ISSUE THREAD

**Issue by ergrelet** [Vector35/community-plugins#273]
### Plugin Description

The plugin relies on [themida-unmutate](https://github.com/ergrelet/themida-unmutate) to deobfuscate functions obfuscated by Themida's code mutation. The user needs to set the cursor to the entry point of the obfuscated function (or portion of code if the function is partially mutated) and then run the "Deobfuscate ..." action.

### Plugin Repository URL

Repo URL: https://github.com/ergrelet/themida-unmutate-bn

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Thanks! I've updated the plugin manager, should be live in ~5m
