### ISSUE TITLE
[New Plugin]: MCLF Loader

### ISSUE THREAD

**Issue by v-rzh** [Vector35/community-plugins#276]
### Plugin Description

This plugin adds support for the Mobicore Loader Format. MCLF is used by MobiCore secure drivers and trusted applications.

### Plugin Repository URL

Repo URL: https://github.com/v-rzh/mclf-binja-loader

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Sorry for the delay, this plugin has been added.
