### ISSUE TITLE
[New Plugin]: BinAssist - Yet another LLM plugin

### ISSUE THREAD

**Issue by jtang613** [Vector35/community-plugins#280]
### Plugin Description

A plugin that provides LLM helpers to explain code and assist in RE.

### Description:
This is a LLM plugin aimed at enabling the use of local LLM's (ollama, text-generation-webui, lm-studio, etc) for assisting with binary exploration and reverse engineering. It supports any OpenAI v1-compatible API. Recommended models are LLaMA-based models such as llama3.1:8b, but others should work as well.

Current features include:

- Explain the current function - Works at all IL levels.
- Explain the current instruction - Works at all IL levels.
- General query - Query the LLM directly from the UI.
- Propose actions - Provide a list of proposed actions to apply.
- Function calling - Allow agent to call functions to navigate the binary, rename functions and variables.
- RLHF dataset generation - To enable model fine tuning.
- RAG augmentation - Supports adding contextual documents to refine query effectiveness.
- Settings to modify API host, key, model name and max tokens.

Future Roadmap:

- Agentic assistant - Use Autogen or similar framework for self-guided binary RE.
- Model fine tuning - Leverage the RLHF dataset to fine tune the model.

### Plugin Repository URL

https://github.com/jtang613/BinAssist

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Thanks for the submission! Just added the plugin now. As a heads up in the future, you can remove the longdescription field and the plugin manager will just pull the data from the readme instead of having to maintain both. 

Also, highly recommend you switch the API key fields to use the `hidden` [bool](https://api.binary.ninja/binaryninja.settings-module.html#binaryninja.settings.Settings) on the key.

**Comment by psifertex** [comment]
Actually, the import failed. Please double check that the release was done appropriately (I recommend using the `gh` cli tool, or https://github.com/Vector35/release_helper)

**Comment by jtang613** [comment]
Thanks for the quick turnaround! Great advice - I'll make sure to incorporate that into the next release.

**Comment by psifertex** [comment]
Well, you might be able to do that sooner rather than later. 😉

**Comment by jtang613** [comment]
I

> Actually, the import failed. Please double check that the release was done appropriately (I recommend using the `gh` cli tool, or https://github.com/Vector35/release_helper)

I used the instructions here: https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release
I'll try a point release using the helper.

**Comment by jtang613** [comment]
The helper is giving me odd HTTP 404 errors. Does your import script give any hints as to what I've done wrong?

**Comment by psifertex** [comment]
```
ERROR: tang613/BinAssist, Couldn't get release information. Likely the user created a tag but no associated release.
```
Generated by:

https://github.com/Vector35/community-plugins/blob/master/generate_index.py#L56

**Comment by jtang613** [comment]
I apologize - this is my first BN plugin. I do have a release tagged with 0.1.0. Is this not the correct format?
https://github.com/jtang613/BinAssist/releases

**Comment by psifertex** [comment]
Let me investigate some.

**Comment by psifertex** [comment]
D'oh, my apologies. [Copy/paste failure](https://github.com/Vector35/community-plugins/commit/e66afe40e5d6c3aef1c56d6c34bf139c3d4310db). 😞 Should be live shortly! You didn't do anything wrong, sorry about that.
