### ISSUE TITLE
[New Plugin]: PSVitaLoader

### ISSUE THREAD

**Issue by computerman00** [Vector35/community-plugins#283]
### Plugin Description

A Binary Ninja Plugin for PRX2 PS Vita eboot.bin ELFs.

Dynamic linking of modules on the PS Vita [is performed](https://wiki.henkaku.xyz/vita/NID#Usage) by NID(Numeric Identifier) of a function or variable instead of names. The primary purpose of this plugin is to resolve all import/export function/variable names, create symbols for them, and load them back into the default ELF BinaryView at their respective position. This plugin will also add PS Vita(PRX2) specific datatypes with locations in the binary resolved(if applicable). Additionally, this plugin attempts to do some cleanup resulting from the decompilation of the mixed ARMv7/thumb2 instruction sets, removing some misaligned/junk instructions in places where there should have been in-line data.

Included is a combined NID database from [vitasdk](https://github.com/vitasdk/vita-headers/tree/master/db/360) used for the function and variable name resolution/lookup. A optional header file is included as well, also combined from vitasdk's [vita-headers](https://github.com/vitasdk/vita-headers/tree/master/include), if supplied all datatypes will be imported along with the sce* functions proper return type, argument names, and argument types. 

### Plugin Repository URL

Repo URL: https://github.com/computerman00/BinaryNinja-PSVitaLoader

### Real Release

- [X] I have made a real release

**Comment by computerman00** [comment]
I'm not sure if the above issue is automatically parsed so adding in a comment.

I went through a few of the plugin submission issues and noted that not including the `longdescription` field will result in the README getting pulled instead. Doing this, the `generate_plugininfo.py -v plugin.json` check fails but I did check out a few releases and noticed that they had skipped the field - let me know if this is an issue and I will resolve it as soon as I can. 

On the same note, my README might be a bit too verbose, if you think that is the case I will add a shorter `longdescription`. I do hope to add a wiki that I can move(and expand) the examples into. 

Please do let me know if you have any feedback or find any issues in the submission. Thanks for your time!

**Comment by psifertex** [comment]
Sorry for the delay, the plugin has now been added!
