### ISSUE TITLE
[New Plugin]: GrammaTech Intermediate Representation for Binaries exporter

### ISSUE THREAD

**Issue by adrianherrera** [Vector35/community-plugins#284]
### Plugin Description

Exports the BNDB to GrammaTech's Intermediate Representation for Binaries ([GTIRB](https://grammatech.github.io/prj/gtirb/)).

### Plugin Repository URL

https://github.com/adrianherrera/binaryninja-gtirb

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Sorry for the delay -- please correct the mis-matched strings between the [version in the plugin.json](https://github.com/adrianherrera/binaryninja-gtirb/blob/main/plugin.json#L30) vs the actual [release](https://github.com/adrianherrera/binaryninja-gtirb/releases). I recommend removing the "v" in the release as that's the preferred format.

**Comment by adrianherrera** [comment]
Oh good pick up! Will do

**Comment by adrianherrera** [comment]
Alrighty all fixed!

**Comment by psifertex** [comment]
Sorry for the delay -- GH was doing some shenanigans with their action base images that I had to [work around](https://github.com/Vector35/community-plugins/commit/94d2a9749096240e41edf4ea27d35aebb8f9c581) and then [undo](https://github.com/Vector35/community-plugins/commit/4d9460bba7a8d3b32d182df2299b5609da9a0d3c) the work-around!

**Comment by plafosse** [comment]
BTW @adrianherrera Your link to the blog post here is broken: https://grammatech.github.io/prj/gtirb/
