### ISSUE TITLE
[New NATIVE Plugin]: NEC850 Architecture to support Renesas RH850/V850 files

### ISSUE THREAD

**Issue by Martyx00** [Vector35/community-plugins#285]
### Plugin Description

This plugin provides native implementation of the architecture plugin to support Renesas RH850/V850 binaries and thus is suitable for processing large files.

### Plugin Repository URL

Repo URL: https://github.com/Accenture/NEC850_Architecture

**Comment by psifertex** [comment]
Sorry. That might be on me. I don't remember if I made a new native issue that doesn't get auto validated.

**Comment by psifertex** [comment]
You shouldn't need a release for a native plugin.
