### ISSUE TITLE
[New NATIVE Plugin]: NEC850 Architecture Support

### ISSUE THREAD

**Issue by Martyx00** [Vector35/community-plugins#286]
### Plugin Description

This plugin provides native implementation of the architecture to support Renesas RH850/V850 binaries and thus is suitable for processing large files.

### Plugin Repository URL

Repo URL: https://github.com/Accenture/NEC850_Architecture

**Comment by psifertex** [comment]
Added to the plugin manager as a view-only plugin, thanks.
