### ISSUE TITLE
[New Plugin]: Apple Blocks Plugin

### ISSUE THREAD

**Issue by droe** [Vector35/community-plugins#293]
### Plugin Description

Annotation of Apple [libclosure](https://github.com/apple-oss-distributions/libclosure) [blocks](https://clang.llvm.org/docs/BlockLanguageSpec.html).  Type annotation of stack and global blocks, block descriptors, variables closed over, and related function signatures.

### Plugin Repository URL

Repo URL: https://github.com/droe/binja-blocks

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Looks great, added. Thanks!
