### ISSUE TITLE
[New Plugin]: bninja-ps3

### ISSUE THREAD

**Issue by valters-tomsons** [Vector35/community-plugins#294]
### Plugin Description

This plugin provides a loader for analyzing Playstation 3 PPU executables. 

### Plugin Repository URL

https://github.com/valters-tomsons/bninja-ps3

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Sorry for the delay, missed this previously.

**Comment by psifertex** [comment]
Whoops, I apparently didn't miss it, just missed closing the issue. :-)

https://github.com/Vector35/community-plugins/commit/fc2f4a38d59fe5d4881847404c550154ed1ee8b4
