### ISSUE TITLE
[New Plugin]: permap

### ISSUE THREAD

**Issue by Jepson2k** [Vector35/community-plugins#297]
### Plugin Description

Supports loading .per files into Binary Ninja

### Plugin Repository URL

Repo URL: https://github.com/redballoonsecurity/permap

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Thanks! I just submitted a PR as it looks like you've got a leftover in the readme you should fix and do a re-release. Consider using  https://github.com/Vector35/release_helper to make that process easier.

**Comment by Jepson2k** [comment]
Good catch, I've updated the readme and made a new release

**Comment by psifertex** [comment]
Added previously but forgot to close! Thanks for the submission.
