### ISSUE TITLE
new plugin: i8086

### ISSUE THREAD

**Issue by whitequark** [Vector35/community-plugins#30]
https://github.com/whitequark/binja-i8086/blob/master/plugin.json
It is a feature-complete 16-bit Intel 8086 plugin, providing disassembly and lifting for every instruction the orignial 8086 has. (Except lifting for the weird BCD instructions, but who cares about them anyway.)

**Comment by psifertex** [comment]
Added, thanks. (Though as noted, we now have support built in from Intel XED though we still lack segmentation support)
