### ISSUE TITLE
New binary ninja plugin: Universal annotate

### ISSUE THREAD

**Issue by bkerler** [Vector35/community-plugins#31]
You can download it [here](https://github.com/bkerler/binja-annotate).

It replaces the Annotator and WinAPI-Annotator function annotation plugin, adds python2/python3 support, adds LLIL/MLIL based reg support for ARM architecture. So x86/x64/ARM Windows/Linux supported right now.

It aims for generic architecture and platform function annotation :D

**Comment by bkerler** [comment]
Sure, just renamed it :)

**Comment by psifertex** [comment]
Added a while ago, but forgot to close the ticket.
