### ISSUE TITLE
github plugin folders not redirecting to the plugins themselves 

### ISSUE THREAD

**Issue by Omiyaru** [Vector35/community-plugins#32]
cloning or downloading the zip downloads the folders but nothing that should be in them like the actual plugin links

**Comment by Omiyaru** [comment]
Clone each individually?, cause by what it looks like is that I even when cloning the entire repo, the subfolders are empty

**Comment by joshwatson** [comment]
https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by psifertex** [comment]
Closing this as won't fix -- the ultimate goal is to have a UI for the repo manager in BN itself which is tracked separately at:
https://github.com/Vector35/binaryninja-api/issues/1083
https://github.com/Vector35/binaryninja-api/issues/480
