### ISSUE TITLE
New Plugin: Find and Nop

### ISSUE THREAD

**Issue by made0x78** [Vector35/community-plugins#34]
This plugin provides a simple feature to replace assembly patterns with nop's in the whole binary. This can be useful to defeat simple anti debugging features like breakpoints (int3 instructions) or anti vm mechanism which have the same pattern in the given binary.

https://github.com/made0x78/binaryninja-find_and_nop

**Comment by psifertex** [comment]
Thanks -- one minor request: would you mind renaming to just `find_and_nop`? We're trying to avoid all the plugins starting with "binaryninja" in the name since it is going to clutter the "b" section of the plugin installer UI when we roll that out.

**Comment by made0x78** [comment]
New url: https://github.com/made0x78/find_and_nop

**Comment by psifertex** [comment]
Much appreciated, adding now.

**Comment by made0x78** [comment]
It seems, that the links to my repo are broken. In the readme the repo and the author link to the vector35 repo and the submodule doesn't redirect.

**Comment by psifertex** [comment]
Sorry about that, no idea how it got in that state. Local repo had the submodules reference correct. Should be fixed now.
