### ISSUE TITLE
New plugin: Game Boy ROM loader and disassembler

### ISSUE THREAD

**Issue by icecr4ck** [Vector35/community-plugins#37]
Hello,

I've made a short plugin to load and disassemble Game Boy ROMs in Binary Ninja, I've not implemented the LLIL lifting yet and I don't know if I will have enough time to do it soon. In the meantime, the plugin is still perfectly functional to analyze Game Boy ROMs (at least on the samples I tested).

https://github.com/icecr4ck/bnGB

**Comment by psifertex** [comment]
Thanks! Added.
