### ISSUE TITLE
New plugin: PE Utils

### ISSUE THREAD

**Issue by 404d** [Vector35/community-plugins#38]
I've made a plugin mainly aimed at helping with Windows projects with dependencies on libraries that also needs to be reverse engineered. I'll admit this likely isn't a common workflow, but it does help me a lot.

Right now it just adds symbol names and types from library binary views to the current binary view, and provides some quick utils for reading the IAT/EAT and checking the relationship between binary views.

https://github.com/404d/peutils

**Comment by psifertex** [comment]
Hah! We're actually working on making some of this functionality first-party /very/ soon as a matter of fact, but I'll certainly add the plugin as it is a good stop-gap and might implement things differently.

**Comment by 404d** [comment]
Forgot to test after moving this out of another plugin... I'll fix some stuff up, should be OK by tomorrow :V

**Comment by psifertex** [comment]
Ok, I was just about to push it, I'll hold off until you let me know it's ready.

**Comment by 404d** [comment]
Should be fine now!

**Comment by psifertex** [comment]
done

**Comment by psifertex** [comment]
Thanks!
