### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by ehennenfent** [Vector35/community-plugins#4]
The links in items 2 and 4 under "Contributing Plugins" point to pages which throw a 404 error.

https://github.com/Vector35/community-plugins/blob/master/Vector35/official-plugins/plugins/sample_plugin/plugin.json --> https://github.com/Vector35/sample_plugin/blob/master/plugin.json

https://github.com/Vector35/community-plugins/blob/master/Vector35/community-plugins/issue --> https://github.com/Vector35/community-plugins/issues

**Comment by psifertex** [comment]
Fixed the first ones but for some reason forgot the last one. Thanks for the heads up, all fixed.
