### ISSUE TITLE
A python script to shrink the database

### ISSUE THREAD

**Issue by jeffli678** [Vector35/community-plugins#44]
https://github.com/jeffli678/shrink-binaryninja-db

Motivation: the database grows too fast!

**Comment by psifertex** [comment]
Can you please add a plugin.json so we can add it? Thanks for the plugin! Also, be aware that this will (hopefully) be unnecessary soon as we're working on building this functionality internally.

**Comment by jeffli678** [comment]
Hi, thanks for your response. 

I can definitely add a plugin.json. However, is there any existing API to manipulate the snapshots directly? I did not find it. Or I simply add a menu item so people can click it to shrink the current database? 

I am aware it can be soon deprecated. But it seems still helpful for version 1689. So it is fine for me! Besides, I hope to be able to arbitrarily switch between the snapshots in the official version.

**Comment by jeffli678** [comment]
I added the plugin.json. 

Are there any documents on the "minimumBinaryNinjaVersion" filed? I left it unchanged from the sample plugin. 

If there is a way to know the current path of the database, please let me know. So I can create a menu item for it.

**Comment by psifertex** [comment]
We're actually changing how the minimal version (and many other fields) work as we prepare to roll out the built-in UI for managing plugins shortly, but we're also releasing a tool that will help people generate the new plugin file and will do a blog post walking through the implementation. This is perfect in the meantime. 

No, unfortunately there are no official APIs for the snapshot management at this point, I'd recommend just adding a menu, though you could also use the built in UI elements to let the user select a file/display output if you wanted, for example. 

Added the plugin, thanks.
