### ISSUE TITLE
update bnil-graph to v1.2.0

### ISSUE THREAD

**Issue by withzombies** [Vector35/community-plugins#49]
released today

https://github.com/withzombies/bnil-graph/tree/v1.2.0

**Comment by psifertex** [comment]
Thanks, updated.

**Comment by withzombies** [comment]
I don't see my plugin in the plugin manager

**Comment by withzombies** [comment]
https://github.com/withzombies/bnil-graph/releases/tag/v1.2.0

**Comment by plafosse** [comment]
Thats cause he never actually added it :P It ther enow though.

**Comment by withzombies** [comment]
I updated bnil-graph to use the new plugin.json format and pushed a new release: https://github.com/withzombies/bnil-graph/releases/tag/v1.2.1
