### ISSUE TITLE
Explain Instruction

### ISSUE THREAD

**Issue by ehennenfent** [Vector35/community-plugins#5]
https://github.com/ehennenfent/binja_explain_instruction

My instruction explanation plugin has reached a reasonable standard of completeness. Note that while it still includes the unsupported UI hacks, it can fall back to a builtin message box whenever there are issues importing PyQt, so it should be usable on platforms other than Linux. Could still use someone to confirm that it works on Windows though.

**Comment by psifertex** [comment]
Thanks! Done.
