### ISSUE TITLE
Submitting/Resubmitting multiple plugins

### ISSUE THREAD

**Issue by zznop** [Vector35/community-plugins#52]
Take the `1.0` tag for the plugins below

https://github.com/zznop/bnida
https://github.com/zznop/bn-genesis
https://github.com/zznop/bn-kallsyms
https://github.com/zznop/binjago
https://github.com/zznop/bn-recursion

**Comment by plafosse** [comment]
Looks like you created a tag but no associated release. You can do this from the browser like this: https://help.github.com/en/articles/creating-releases or you can use the hub app to do it from the command line: https://github.com/github/hub

**Comment by psifertex** [comment]
also, bnida won't actually load since plugins are required to have an init -- only files dropped directly in the main folder are loaded immediately otherwise it's treated like a module.

**Comment by zznop** [comment]
@plafosse what are you referring to? If I click https://github.com/zznop/bnida/releases/tag/1.01 It shows the tag as a release (same with all 5 of those projects). I didn't do all the github-specific stuff through the UI, just created and pushed tags from the command line. Is the github-specific stuff necessary?

@psifertex no init was intentional because it also had two IDA scripts in the directory. However, now that you have a plugin manager, I went ahead and added an `__init__.py` for BN, and moved the IDA scripts into their own sub-directory.

**Comment by zznop** [comment]
Oh yeah, and use 1.01 for bnida, 1.0 for the rest

**Comment by plafosse** [comment]
Github shows it as a release but its isn't a release according to the github API which is what we use (check out https://api.github.com/repos/zznop/bnida/releases). You do have to go do the github-specific stuff which is really easy if you have the hub tool. `apt get install hub` or `brew install hub` then `hub release create v1.0`

**Comment by zznop** [comment]
@plafosse Ok, hopefully it's all good to go now

**Comment by plafosse** [comment]
Good to go, Thanks!
