### ISSUE TITLE
AVR architecture plugin

### ISSUE THREAD

**Issue by fluxchief** [Vector35/community-plugins#54]
https://github.com/fluxchief/binaryninja_avr/releases/tag/0.2

**Comment by plafosse** [comment]
Looks like you created a tag but no associated release. You can do this from the browser like this: https://help.github.com/en/articles/creating-releases or you can use the hub app to do it from the command line: https://github.com/github/hub. Check  https://api.github.com/repos/fluxchief/binaryninja_avr/releases to ensure you have a release.

**Comment by fluxchief** [comment]
Fixed

**Comment by plafosse** [comment]
Added
