### ISSUE TITLE
[NewPlugin]  mechanicalnull sourcery_pane v0.1

### ISSUE THREAD

**Issue by mechanicalnull** [Vector35/community-plugins#57]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag.

I either used the UI, or the `hub` command to create a _real_ release.

Author: mechanicalnull
Repo name: sourcery_pane
Release: v0.1 (https://github.com/mechanicalnull/sourcery_pane/releases/tag/v0.1)

**Comment by plafosse** [comment]
❤️ Thanks done!
