### ISSUE TITLE
[NewPlugin] jofra format-string-finder-binja v1.0

### ISSUE THREAD

**Issue by Vasco-jofra** [Vector35/community-plugins#58]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I used the `hub` command to create a _real_ release.

Author: jofra
Repo name: https://github.com/Vasco-jofra/format-string-finder-binja
Release: https://github.com/Vasco-jofra/format-string-finder-binja/releases/tag/v1.0

**Comment by psifertex** [comment]
Added, thanks!
