### ISSUE TITLE
Aug. 2017 Submissions

### ISSUE THREAD

**Issue by ehennenfent** [Vector35/community-plugins#6]
## https://github.com/ehennenfent/binja_dynamics
Adds a PyQt5 frontend to Binjatron, including a register viewer, traceback viewer, and live memory viewer with stack frame highlighting.

## https://github.com/ehennenfent/binja_arch_ref
Adds a simple cheat sheet report to Binja based on the information available in the architecture object.

## https://github.com/ehennenfent/binja_sensei
Uses the RepositoryManager API to automatically install the plugins listed above, along with `binja_explain_instruction`, `Syscaller`, and `Annotator`.

<hr>

One other issue: binja_explain_instruction is linked as a submodule to this repo, but is not included in plugins.json (or README.md). This means that the Repository Manager does not provide a means to install it.

**Comment by peperunas** [comment]
I'll add myself in here!

Here is a disassembler / lifter for the [Pasticciotto](https://github.com/peperunas/pasticciotto) architecture I made. :D

The plugin repo is [here](https://github.com/peperunas/binaryninja-pasticciotto).

**Comment by psifertex** [comment]
All these are added.

**Comment by ehennenfent** [comment]
Looks like pasticciotto has been submodule'd, but hasn't been added to plugins.json yet

**Comment by psifertex** [comment]
Added these to the repo (and readme!) but never marked this as closed.
