### ISSUE TITLE
[NewPlugin]  shareef12 driveranalyzer v1.0.0

### ISSUE THREAD

**Issue by shareef12** [Vector35/community-plugins#63]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I used the UI to create a _real_ release.

Author: Me
Repo name: https://github.com/shareef12/driveranalyzer/releases/tag/v1.0.0
Release: v1.0.0

**Comment by psifertex** [comment]
Thanks for the submission -- added.
