### ISSUE TITLE
[NewPlugin]  404d peutils v1.0

### ISSUE THREAD

**Issue by 404d** [Vector35/community-plugins#64]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I used the `hub` command to create a _real_ release.

Author: Me
Repo name: https://github.com/404d/peutils/releases/tag/v1.0
Release: v1.0

**Comment by psifertex** [comment]
Looks good, thanks! Added to the repo.
