### ISSUE TITLE
[UpdatePlugin]  mark-griffin bncov v1.1

### ISSUE THREAD

**Issue by mark-griffin** [Vector35/community-plugins#65]
I've updated bncov to conform with the new plugin manager guidelines (https://github.com/ForAllSecure/bncov/releases/tag/v1.1), please add the new version to the repository.

Author: Mark Griffin
Repo name: bncov
Release: v1.1

**Comment by psifertex** [comment]
Thanks for updating it, sorry for the delay as several of us were traveling last week. Plugin has been added.
