### ISSUE TITLE
[NewPlugin]  ehntoo binaryninja-svd v1.0

### ISSUE THREAD

**Issue by ehntoo** [Vector35/community-plugins#66]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: https://github.com/ehntoo/binaryninja-svd/releases/tag/v1.0
Release: v1.0

Finally got around to updating at least one of my plugins for inclusion in the new plugin manager. More should follow soon.

**Comment by psifertex** [comment]
Thanks! Looking forward to it. Plugin has been added.
