### ISSUE TITLE
[NewPlugin]  joshwatson binaryninja-msp430 0.4

### ISSUE THREAD

**Issue by joshwatson** [Vector35/community-plugins#67]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: joshwatson
Repo name: binaryninja-msp430
Release: 0.4

**Comment by psifertex** [comment]
Thanks, updated.
