### ISSUE TITLE
[NewPlugin]  tchebb binaryninja-offsetview v0.2

### ISSUE THREAD

**Issue by tchebb** [Vector35/community-plugins#68]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: binaryninja-offsetview
Release: v0.2

**Comment by bpotchik** [comment]
Have you tried "Open with Options" in Binary Ninja? We support rebasing in the UI and headless now for supported file formats and raw files.

**Comment by tchebb** [comment]
Oh, that's great to hear! I let my subscription lapse a while ago so didn't know about the new feature. That could be a reason to renew, though. Until then, I'll keep using this for myself :)
