### ISSUE TITLE
[UpdatePlugin]  $ForAllSecure $bncov $1.2

### ISSUE THREAD

**Issue by mark-griffin** [Vector35/community-plugins#70]
Please update my plugin:

Author: Mark Griffin
Repo name: bncov
Release: https://github.com/ForAllSecure/bncov/releases/tag/v1.2

**Comment by psifertex** [comment]
Looks like you made a tag, but not a release: https://github.com/ForAllSecure/bncov/releases

See: https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release

**Comment by mark-griffin** [comment]
Ugh, yep.  hub aborts releases with a blank release title.  Fixed: https://github.com/ForAllSecure/bncov/releases/tag/v1.2

**Comment by psifertex** [comment]
Done, thanks!
