### ISSUE TITLE
[NewPlugin]  murx- devi v0.1

### ISSUE THREAD

**Issue by murx-** [Vector35/community-plugins#71]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: murx-
Repo name: devi
Release: v0.1

**Comment by psifertex** [comment]
Thanks for the submission. Just to be clear though the plugin that should be added is `devi_binja`, not `devi` correct?

**Comment by murx-** [comment]
good point, yes. Once https://github.com/Vector35/community-plugins/issues/23 is resolved i guess it would make sense to put everything in one repository again so the frida part is also included. 
I also managed to forget the link because i was so excited for the new feature :D 
Here the link just to be certain:
https://github.com/murx-/devi_binja/releases/tag/v0.1

**Comment by psifertex** [comment]
Also, just a heads up that I haven't added this yet as a current bug in our implementation means that plugins with characters (like `-`) that aren't compatible with python symbols in github usernames won't load. Will likely resolve both the sub-folder and that issue at the same time.

**Comment by psifertex** [comment]
FYI, this got resolved a while ago (I think with the move to python3) and I forgot to close the ticket out. Thanks for the plugin!
