### ISSUE TITLE
[NewPlugin]  bowline90 Instruction_Slicer v1.0

### ISSUE THREAD

**Issue by bowline90** [Vector35/community-plugins#72]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Andrea Ferraris
Repo name: Instruction_Slicer
Release: [v1.0](https://github.com/bowline90/Instruction_Slicer/releases/tag/v1.0)

**Comment by psifertex** [comment]
Thanks, added.
