### ISSUE TITLE
[NewPlugin]  toolCHAINZ DUMB v1.0.1

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/community-plugins#76]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: toolCHAINZ
Repo name: [DUMB](https://github.com/toolCHAINZ/DUMB)
Release: v1.0.1

**Comment by toolCHAINZ** [comment]
Fixed a couple typos, so I just incremented the version in this issue, since it's not closed yet.

**Comment by psifertex** [comment]
Thanks! I forgot to close it after adding. :-)
