### ISSUE TITLE
Types Parser

### ISSUE THREAD

**Issue by chame1eon** [Vector35/community-plugins#8]
Hi,

I have written a plugin to integrate a C parser with Binary Ninja, for parsing C header files:

https://github.com/chame1eon/binaryninja-types-parser

Let me know if you want me to make any changes to it.

Thanks.

**Comment by psifertex** [comment]
Closing for real this time. :-P 

I pulled the plugin, though I'm curious (I haven't looked closely) how is this different from https://api.binary.ninja/binaryninja.platform-module.html?highlight=parse#binaryninja.platform.Platform.parse_types_from_source_file ?

**Comment by chame1eon** [comment]
Oh :(. It is no different at all. I wish I had seen that part of the API, then I would not have wasted my time making that plugin! Oh well. Sorry about this. Are you okay to remove it from the plugins? Seems little point in having a duplicate feature.

**Comment by psifertex** [comment]
Yeah, I'll go ahead and pull it. No worries, consider it a useful learning experience. :-)
