### ISSUE TITLE
[NewPlugin]  CleanTricks

### ISSUE THREAD

**Issue by janbbeck** [Vector35/community-plugins#81]
Please add my plugin to the repository.

CleanTricks is a plugin to clean up some common obfuscation techniques (dirty tricks). There is an empty template included as well to be able to easily add your own, because there are many many obfuscations out there. However, often they get reused or slightly modified, and then it is useful to have a starting point/example. Pull requests are very welcome.

Author: Jan Beck
Repo name: https://github.com/janbbeck/CleanTricks
Release: 1.0

**Comment by psifertex** [comment]
added, thanks!
