### ISSUE TITLE
[NewPlugin] Specter idc_importer v1.1

### ISSUE THREAD

**Issue by Cryptogenic** [Vector35/community-plugins#83]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Updated the old IDC Importer plugin to be compatible with the new plugin metadata system. Also updated it to use Python 3 and to port all comments.

https://github.com/Cryptogenic/idc_importer

Author: Specter
Repo name: idc_importer
Release: v1.1

**Comment by psifertex** [comment]
Thanks! Added.
