### ISSUE TITLE
[NewPlugin]  404d autoutils v0.1

### ISSUE THREAD

**Issue by 404d** [Vector35/community-plugins#87]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: autoutils
Release: v0.1

**Comment by psifertex** [comment]
Added , thanks! I sense a naming convention from your pulgins. 😉

**Comment by 404d** [comment]
~~My imagination knows no bounds~~ When they're as small as they are now I'd rather try to make it appropriately general so that I have a place to put future snippets 😅

Cheers, and thanks for HLIL!
