### ISSUE TITLE
[NewPlugin] jmprdi binja-division-deoptimization v0.1.1

### ISSUE THREAD

**Issue by nbanmp** [Vector35/community-plugins#90]
Hey, i've written a division & modulo deoptimization plugin. Could you add it to the repository?

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: jmprdi
Repo name: binja-division-deoptimization
Release: v0.1.1

# Link To Release:
https://github.com/jmprdi/binja-division-deoptimization/releases/tag/v0.1.1

**Comment by psifertex** [comment]
Thanks! Added.
