### ISSUE TITLE
[UpdatePlugin]  jmprdi Division Deoptimizer v0.1.2

### ISSUE THREAD

**Issue by nbanmp** [Vector35/community-plugins#91]
Please update my deoptimizer plugin, with a prettier plugin.json long description.

https://github.com/jmprdi/binja-division-deoptimization/releases/tag/v0.1.2

**Comment by nbanmp** [comment]
wait oops :facepalm:

**Comment by nbanmp** [comment]
Okay, we're good now, go ahead and update it.

**Comment by psifertex** [comment]
All set, thanks!
