### ISSUE TITLE
[NewPlugin]  atxsinn3r BinjaHLILDump v1.0

### ISSUE THREAD

**Issue by atxsinn3r** [Vector35/community-plugins#92]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: atxsinn3r
Repo name: BinjaHLILDump
Release: v1.0
Link: https://github.com/atxsinn3r/BinjaHLILDump/releases/tag/v1.0

**Comment by psifertex** [comment]
Whoops, sorry for the delay! Been a busy few weeks with the 2.0 release. :-) 

I'm adding it to the plugin manager now, thanks. Please note that for future releases, we're trying to standardize on versions NOT having the "v" at the beginning of the release and the version string. I realize our own blog post was originally sending mixed messages on that but we're trying to normalize moving forward!

**Comment by atxsinn3r** [comment]
Thanks for letting me know. Will keep that in mind next time. And congrats on 2.0!
