### ISSUE TITLE
[UpdatePlugin]  Martin Petran (Martyx00) VulnFanatic v2.0

### ISSUE THREAD

**Issue by Martyx00** [Vector35/community-plugins#96]
Please update my plugin:

Author: Martin Petran (Martyx00)
Repo name: VulnFanatic
Release: https://github.com/Martyx00/VulnFanatic/releases/tag/v2.0

I promise this is the real release :)

**Comment by psifertex** [comment]
Is the HLIL usage optional and will it fail gracefully if it's not there? If not, might want to update the minimum version to 2166 since that was the first stable with HLIL. Or you could check the tags on the api repo to have the minimum be the first dev branch with HLIL

**Comment by Martyx00** [comment]
Thanks, updated to 2166 in both repo and release :)

**Comment by psifertex** [comment]
I'm adding it to the plugin manager now, thanks. Please note that for future releases, we're trying to standardize on versions NOT having the "v" at the beginning of the release and the version string. I realize our own blog post was originally sending mixed messages on that but we're trying to normalize moving forward!
