### ISSUE TITLE
HLIL Dump Bug: Not properly handling function names

### ISSUE THREAD

**Issue by tekwizz123** [Vector35/community-plugins#98]
@atxsinn3r It seems your plugin doesn't handle functions with odd names:

```
Dumping function: FixupGrayScan
Dumping function: EditionUpdateInputTransformFromHitTest
Dumping function: InputTransform::SetCompositionInput
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\*censored*\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 731, in run
    self.task.run()
  File "C:\*(censored*\AppData\Roaming\Binary Ninja\repositories\community\plugins\atxsinn3r_BinjaHLILDump\__init__.py", line 33, in run
    f = open(dest_name, 'w')
OSError: [Errno 22] Invalid argument: 'C:/*censored*/New Win32k/HLIL Dump\\InputTransform::SetCompositionInput'
```

**Comment by psifertex** [comment]
Please file issues like this on the original repository so they can best be handled by the original author. You can even navigate directly to that repo by clicking the name of the plugin in the plugin manager or using links in the table in the readme.

**Comment by atxsinn3r** [comment]
Hi @tekwizz123,

Thanks for reporting the issue, I will address this in the original repository like @psifertex said. So I did a quick test, and it looks like it's because Python cannot handle the `*` character in the file path. For example:

```
>>> f = open("C:/Users/sinn3r/Desktop/te*st.txt", "w")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument: 'C:/Users/sinn3r/Desktop/te*st.txt'
```

I will correct the script.  Thank you guys.

**Comment by tekwizz123** [comment]
@psifertex Sorry I didn't want to submit an issue here, but @atxsinn3r's HLIL Dump repository has its issue tracker disabled so I thought this would be the next best place. Sorry I didn't explain this clearer in the description.

@atxsinn3r I'm not sure if its just the `*` character, that was just placed in there cause I censored out my username. I think it was more the `::` characters which aren't allowed in file or path names.

**Comment by psifertex** [comment]
Ahh, fair enough. I'll re-open it here so we can track it in the meantime.

**Comment by psifertex** [comment]
Looks like that's got it's own issue now. Closing again. 😛 

Thanks everyone.
