### ISSUE TITLE
[NewPlugin]  trib0r3 binja-yara 1.0

### ISSUE THREAD

**Issue by trib0r3** [Vector35/community-plugins#99]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: @trib0r3
Repo name: [trib0r3/binja-yara](https://github.com/trib0r3/binja-yara)
Release: https://github.com/trib0r3/binja-yara/releases/tag/1.0

**Comment by psifertex** [comment]
Thanks! Added.
